### PR TITLE
Refactor file operations to Laravel's illuminate/filesystem

### PR DESCRIPTION
**Pull request by Florisbosch**
Related discussion: https://github.com/opcodesio/log-viewer/discussions/173

# Refactor file operations to Laravel's illuminate/filesystem
This pull request refactors the existing file operations in the codebase to use Laravel's `illuminate/filesystem` package instead. This package provides a more elegant and easy-to-use interface for working with files, as well as additional features such as improved error handling and support for cloud storage services.

## Changes
Replaced all instances of the old file operations with calls to the corresponding methods in `illuminate/filesystem`
Refactored tests to ensure the refactored code works as expected

## Benefits
Improved readability and maintainability of the file-related code
Increased reliability and robustness of the file operations
Added support for cloud storage services like Amazon S3

Please review this pull request and let me know if you have any feedback or suggestions. 

Thanks!

### CODE REVIEW

**Comment by arukompas** [comment]
hey @Florisbosch , thanks for such a great contribution! 👏 

Already merged and ready to ship, **BUT** - before I tag a release, there's 2 things that are still missing for backwards compatibility. I rushed a bit and merged the PR without first double-checking them.

If you have spare time and can help me figure these out faster, I could tag as soon as these are fixed.

## 1. Support for absolute paths is now gone
In the `config('log-viewer.include_paths')` users could add **absolute paths** as well, that may be outside of the current project's directory. This helps a lot in viewing logs from multiple projects on the same server within a single Log Viewer view.

This refactor removed this ability. Adding absolute paths (starting with a forward slash `/` ) no longer loads them into the Log Viewer.

## 2. Tests breaking on Windows platform
I want to make it still works as expected on Windows platform as well. The automated tests are failing on Windows:
https://github.com/opcodesio/log-viewer/actions/runs/3718909917/jobs/6307657155

It seems to be down to `stat failed` error:
```
Reason: SplFileInfo::getMTime(): stat failed for D:\a\log-viewer\log-viewer\vendor\orchestra\testbench-core\laravel\storage\logs\ipjSGzjj9oDgo706.log in D:\a\log-viewer\log-viewer\vendor\league\flysystem\src\UnableToListContents.php:17
```

I've spent some time trying to locate the issue, but I couldn't figure it out yet, so perhaps you have an idea of what it could be?

Thanks!

**Comment by Florisbosch** [comment]
Hi @arukompas,

Thanks for reviewing.

I will take a look at the issues later today when I am at home.

**Comment by didix16** [comment]
Hello @arukompas, do you have any plans to include remote filesystem support like access to S3 folders?

**Comment by arukompas** [comment]
@didix16 it would be great, but I'm not sure how feasible this would be, and if S3 driver allows reading files line by line, because loading a 4GB log file in memory would not be feasible.

I'll have more time by the end of the year, when I'll take on a few bigger tasks for Log Viewer. I'll experiment with S3 as well.

**Comment by didix16** [comment]
Okay. I hope you can experiment with S3 and be included in the future! 

Thanks @arukompas !

**Pull request merged**
