### PR TITLE
Add  log notice and CSS styles

### PR DESCRIPTION
**Pull request by ljdj**
Add log notice and update CSS styles

- Implemented notifications for user actions (notice)
- Overhauled CSS styles for UI consistency
- Enhanced form elements' responsiveness

These changes aim to improve user experience by providing immediate feedback on performed actions and making the interface more intuitive and visually appealing.

### CODE REVIEW

**Comment by arukompas** [comment]
hey @ljdj , this PR contains only the `Notice` level. Not sure what the other 2 points in your description relate to. Did you mean to push more code? Because this PR looks good as it is - but the description confuses me a bit :)

**Comment by ljdj** [comment]
Hello @arukompas,
in fact, the description of the PR is not good (AI error for the information).

Here are the changes made:
- Added the notice level to the folder: LogLevels
- Update of the scss (definition of a color for notice)
- Approximate update (definition of a color for instructions)
- Simply missing the shape of the icon to add according to your taste

I hope the explanation suits you, if the color I predefined does not suit, do not hesitate to modify.

Sincerely.

**Review by arukompas — APPROVED** [review]

**Comment by arukompas** [comment]
@ljdj I agree with the changes, and big thanks for them!
But the AI descriptions weren't any good :) neither first nor second.

I'll tag a new release soon.

**Comment by arukompas** [comment]
**v3.2.0** tagged which now includes the new Notice level styling :)

**Pull request merged**
