### PR TITLE
fix: read mix-manifest.json

### PR DESCRIPTION
**Pull request by mohammadRezaPegah**
check mix-manifest.json from public folder on localhost and public_html on server

### CODE REVIEW

**Comment by arukompas** [comment]
hey @mohammadRezaPegah , can you please explain why these two files were added and how does that help solve a problem? What problem were you facing anyway?

**Comment by mohammadRezaPegah** [comment]
Yes of course, when you run your laravel project on localhost and public folder location is inside the project folder, every thing is fine and we have not any problem but when you send the code on server and migrate public folder files to public_html the package looking for public folder in the resource folder and can not find and read mix-manifest.json and returns publish error: "Log Viewer assets are not published. Please run: php artisan vendor:publish --tag=log-viewer-assets --force".

In fact, package assetes published successfully but in LogViewerService.php@assetsAreCurrent() method we used public_path() method to find and read mix-manifest.json file(public_path() by default return's "/home/..../source_code/public"), but now, in LogViewerService.php@assetsAreCurrent(), i first check the public folder(support localhost) and after that i checked public_html folder(support server) and if i cant find mix-manifest.json in any of this path's, the application return's assets publish error.

With this solution user does not need to change public_path() return or change any other configs.

**Comment by arukompas** [comment]
@mohammadRezaPegah , you should not "migrate" anything when deploying to a production server. Your apache/nginx configuration should just serve the app from the `public` folder instead.

For example, if you have deployed your app to `/var/www/example.com` folder, which has the standard Laravel structure like app, vendor, public, etc., then you would configure your Apache like so:
```
    DocumentRoot /var/www/example.com/public
```

Or in nginx:
```
    root /var/www/example.com/public;
```

With this in mind, I'm going to reject this PR because it is not a solution to your problem.

Hopefully this helps! 😄

**Comment by mohammadRezaPegah** [comment]
Very good, I'll check this.
Tank's for your time

**Pull request closed without merging**
